apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airbyte
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: airbyte
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://airbytehq.github.io/helm-charts
    targetRevision: 0.43.6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true