apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: airflow
    helm:
      values: values/airflow/values.yaml
    repoURL: https://airflow.apache.org/
    targetRevision: 1.7.0